# coding: utf-8

"""
    SimpleCalc

    No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.default_api import DefaultApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.default_api.DefaultApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_a_b_op_get(self):
        """Test case for a_b_op_get

        """
        pass

    def test_root_get(self):
        """Test case for root_get

        """
        pass

    def test_root_post(self):
        """Test case for root_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
