/* 
 * SimpleCalc
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Input
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class InputTests
    {
        // TODO uncomment below to declare an instance variable for Input
        //private Input instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Input
            //instance = new Input();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Input
        /// </summary>
        [Test]
        public void InputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Input
            //Assert.IsInstanceOfType<Input> (instance, "variable 'instance' is a Input");
        }


        /// <summary>
        /// Test the property 'A'
        /// </summary>
        [Test]
        public void ATest()
        {
            // TODO unit test for the property 'A'
        }
        /// <summary>
        /// Test the property 'B'
        /// </summary>
        [Test]
        public void BTest()
        {
            // TODO unit test for the property 'B'
        }
        /// <summary>
        /// Test the property 'Op'
        /// </summary>
        [Test]
        public void OpTest()
        {
            // TODO unit test for the property 'Op'
        }

    }

}
