/* 
 * SimpleCalc
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */


using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using IO.Swagger.Api;
using IO.Swagger.Model;
using IO.Swagger.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing Output
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class OutputTests
    {
        // TODO uncomment below to declare an instance variable for Output
        //private Output instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Output
            //instance = new Output();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Output
        /// </summary>
        [Test]
        public void OutputInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Output
            //Assert.IsInstanceOfType<Output> (instance, "variable 'instance' is a Output");
        }


        /// <summary>
        /// Test the property 'C'
        /// </summary>
        [Test]
        public void CTest()
        {
            // TODO unit test for the property 'C'
        }

    }

}
